# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_server_window(object):
    def setupUi(self, server_window):
        server_window.setObjectName("server_window")
        server_window.resize(461, 182)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        server_window.setFont(font)
        server_window.setStyleSheet("background-color: rgb(32, 31, 38);")
        self.centralwidget = QtWidgets.QWidget(server_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(35, 20, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(193, 195, 154);")
        self.label.setObjectName("label")
        self.IP_host = QtWidgets.QLineEdit(self.centralwidget)
        self.IP_host.setGeometry(QtCore.QRect(122, 21, 308, 28))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.IP_host.setFont(font)
        self.IP_host.setStyleSheet("color: rgb(193, 195, 154);")
        self.IP_host.setText("")
        self.IP_host.setObjectName("IP_host")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(43, 62, 48, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(193, 195, 154);")
        self.label_2.setObjectName("label_2")
        self.Port = QtWidgets.QLineEdit(self.centralwidget)
        self.Port.setGeometry(QtCore.QRect(122, 67, 308, 28))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.Port.setFont(font)
        self.Port.setStyleSheet("color: rgb(193, 195, 154);")
        self.Port.setText("")
        self.Port.setObjectName("Port")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(10, 115, 441, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        self.start_button.setFont(font)
        self.start_button.setStyleSheet("color: rgb(193, 195, 154);")
        self.start_button.setObjectName("start_button")
        server_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(server_window)
        QtCore.QMetaObject.connectSlotsByName(server_window)

    def retranslateUi(self, server_window):
        _translate = QtCore.QCoreApplication.translate
        server_window.setWindowTitle(_translate("server_window", "Server"))
        self.label.setText(_translate("server_window", "IP Host:"))
        self.label_2.setText(_translate("server_window", "Port:"))
        self.start_button.setText(_translate("server_window", "Start server"))
